/**
 * 把 github-markdown-css 的两个单主题文件冻结成 JS 字符串模块。
 *
 * 为什么是单主题文件而不是合并版：合并版 github-markdown.css 的 dark 规则嵌在
 * @media (prefers-color-scheme: dark) 里，在浅色系统上无论放哪都不生效（SPEC §9.2）。
 * 下面的检查就是把这句话从注释变成会失败的东西。
 *
 * 为什么内联成 JS 字符串而不是 `import s from './x.css' with { type: 'css' }`：
 * 后者强迫每个消费者的打包器支持 CSS import 属性（SPEC §9.3、决策台账 17）。
 *
 * 跑法：npm run gen:theme-css -w @readit/element
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

const require = createRequire(import.meta.url)
const pkgJsonPath = require.resolve('github-markdown-css/package.json')
const pkgDir = dirname(pkgJsonPath)
const version = (JSON.parse(readFileSync(pkgJsonPath, 'utf8')) as { version: string }).version

function readTheme(file: string): string {
  const text = readFileSync(join(pkgDir, file), 'utf8')
  if (text.includes('@media (prefers-color-scheme')) {
    throw new Error(
      `readit: ${file} 含 @media (prefers-color-scheme …)。单主题文件不该有——` +
        '取到的多半是合并版 github-markdown.css，它在浅色系统上放哪都不生效。见 SPEC §9.2。',
    )
  }
  if (!text.includes('.markdown-body')) {
    throw new Error(`readit: ${file} 里没有 .markdown-body，不像是 github-markdown-css`)
  }
  return text
}

const light = readTheme('github-markdown-light.css')
const dark = readTheme('github-markdown-dark.css')

const source = [
  '// @generated by scripts/gen-theme-css.ts —— 不要手改。',
  `// 源：github-markdown-css@${version}（github-markdown-light.css / github-markdown-dark.css）`,
  '// 重新生成：npm run gen:theme-css -w @readit/element',
  '',
  `export const THEME_CSS_VERSION = ${JSON.stringify(version)}`,
  `export const LIGHT_CSS_BYTES = ${Buffer.byteLength(light, 'utf8')}`,
  `export const DARK_CSS_BYTES = ${Buffer.byteLength(dark, 'utf8')}`,
  `export const LIGHT_CSS = ${JSON.stringify(light)}`,
  `export const DARK_CSS = ${JSON.stringify(dark)}`,
  '',
].join('\n')

writeFileSync(new URL('../src/styles/theme-css.ts', import.meta.url), source)
process.stdout.write(
  `theme-css.ts: light ${Buffer.byteLength(light, 'utf8')} B, dark ${Buffer.byteLength(dark, 'utf8')} B\n`,
)
