import { writeFileSync } from 'node:fs'
import { extractSvgStylesheet } from '@readit/math/introspect'

const css = extractSvgStylesheet()
// Emitted as JSON string literals joined by '\n', NOT as a template literal:
// the sheet contains `content: "\A"` and a template literal silently eats that backslash.
const lines = css.split('\n').map((l) => '  ' + JSON.stringify(l)).join(',\n')
const file = `// GENERATED by tools/gen-svg-stylesheet.ts — do not edit by hand.
// Source: @mathjax/src@4.1.3 SVG output jax + @mathjax/mathjax-tex-font@4.1.3,
// with fontCache:'none', tags:'none', displayOverflow:'scroll'.
// Regenerate: npx vite-node tools/gen-svg-stylesheet.ts
// packages/math/test/svg-stylesheet.test.ts asserts this equals the live output.

export const SVG_STYLESHEET: string = [
${lines},
].join('\\n')

export const SVG_STYLESHEET_BYTES = ${Buffer.byteLength(css)}
`
writeFileSync(new URL('../packages/math/src/svg-stylesheet.ts', import.meta.url), file)
console.log('wrote', Buffer.byteLength(css), 'bytes of CSS')
